name: CI & CD

on:
  push:
    branches: [main]      # triggers on every push to main
  pull_request:
    branches: [main]      # optional: run tests for PRs

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    env:
      # These come from repo secrets; fall back to SQLite for CI
      DATABASE_URL: file:/data/db.sqlite
      JWT_SECRET: ${{ secrets.JWT_SECRET || 'ci-secret' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    # ---------- PREPARE DATABASE (SQLite) ----------
    - name: Install dependencies
      run: npm ci

    - name: Prepare Prisma & seed DB
      run: |
        npx prisma generate
        npx prisma db push
        npm run db:seed

    # ---------- TESTS ----------
    - name: Run unit tests
      run: npm test -- --runInBand

    - name: Install Playwright browsers
      if: success()
      run: npx playwright install --with-deps

    - name: Run E2E tests
      if: success()
      run: npm run test:e2e

    # ---------- BUILD ----------
    - name: Build production bundle
      if: success()
      run: npm run build

    # ---------- DEPLOY ----------
    - name: Trigger Render deploy
      if: success() && github.ref == 'refs/heads/main'
      run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
